### ISSUE TITLE
Citations not being updated

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/bee-interaction-database#11]
@jhpoelen I see special character issues from BID still in GloBI, yet I believe they were removed. 

Here is the GloBI view:
<img width="1171" alt="Screen Shot 2020-10-21 at 2 36 07 PM" src="https://user-images.githubusercontent.com/1044474/96790002-f0305700-13aa-11eb-9da8-e7eaf01e2df7.png">

But here is the tsv in the repository:
<img width="809" alt="Screen Shot 2020-10-21 at 2 36 32 PM" src="https://user-images.githubusercontent.com/1044474/96790173-34bbf280-13ab-11eb-9967-1feed18b6da8.png">

**Comment by jhpoelen** [comment]
@seltmann Thanks for sharing. The examples with funny characters are indexed from https://github.com/elntangle/bee-interaction-database and https://github.com/rnbehm/bee-interaction-database . Is this where you got the tsv from ?

**Comment by seltmann** [comment]
Lightbulbs! I was assuming that the only location GloBI was getting data is from this repository. globalbioticinteractions/bee-interaction-database because it is in the globalbioticinteractions repo. It did not occur to me that the forks would also be indexed and the students (who are now not working on the project) forked the globi.json. What is the fix? Delete the globi.json from the other repos?

**Comment by seltmann** [comment]
All of the data from https://github.com/elntangle/bee-interaction-database and https://github.com/rnbehm/bee-interaction-database are merged into globalbioticinteractions/bee-interaction-database

**Comment by jhpoelen** [comment]
GloBI does not forget ; ) 

Deprecation of datasets is an open issue (https://github.com/globalbioticinteractions/globalbioticinteractions/issues/372) . 

Some ideas come to mind:

1. ask your students to zero out the interactions.tsv (no changed needed)
2. introduce a setting in globi.json like: ```"deprecated": true```
3. curate a list of datasets that are publicly shown on https://globalbioticinteractions.org .

Curious to hear what you think.

**Comment by seltmann** [comment]
What does "zero out mean?"

**Comment by jhpoelen** [comment]
Remove all records except the header.

**Comment by jhpoelen** [comment]
, but keep the repository. This is a crude way to make a "tombstone" (actual technical term).

**Comment by seltmann** [comment]
Also will change the globi.json so that it is:
{ 
  "_comment": "Bee (Anthophila) biotic interaction database.",
  "citation": "Seltmann, Katja C. 2020. Biotic species interactions about bees (Anthophila) manually extracted from literature."
  "deprecated": true
}

**Comment by jhpoelen** [comment]
@seltmann exactly! perhaps a fancier tombstone. This leave the provider in charge of whether GloBI should index or not.

**Comment by seltmann** [comment]
Exactly what I want on my tombstone "deprecated": true

So, glad to get to the bottom of this. It was not intuitive to me that GloBI also indexed the project forks. Seems risky since forking is public.

**Comment by jhpoelen** [comment]
Ok, I added our ideas in the https://github.com/globalbioticinteractions/globalbioticinteractions/issues/372 . Thanks for bringing this up. Can you work with your students to add this to their globi.json ? Meanwhile, I'll hope to realize this idea. Would you like to keep this issue open until https://github.com/globalbioticinteractions/globalbioticinteractions/issues/372 is implemented?

**Comment by seltmann** [comment]
I already contacted them. Should be updated soon. Will leave open for now. Thanks!

**Comment by seltmann** [comment]
@jhpoelen Both of the forked repos now are tombstones. Question: does GloBI look in subfolders for interaction data? I have a folder called "working datasets" which are old datasets. Does GloBI look inside those for more interactions or just the interactions.tsv that i in the root.

**Comment by jhpoelen** [comment]
@seltmann thanks for helping to mark the datasets as deprecated. 

GloBI does not recurse into folders for additional globi.json or data files. Instead, the default behavior for the default interaction dataset type is to look for interactions.tsv or interactions.csv files in the root of the dataset archive / github repository. Custom dataset types (e.g., mangal.io dataset importer) uses more sophisticated methods to pull in requested resources (e.g., api requests, database queries, etc.).
