### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/bee-interaction-database#3]
@jhpoelen the build for my new interaction db is failing. Suggestions as to why?

**Comment by seltmann** [comment]
travis.ci gives me an error that "There was an error while trying to fetch the log." if that helps

**Comment by jhpoelen** [comment]
travis-ci was doing scheduled maintenance last night and they are working through their backlog. 

https://www.traviscistatus.com/ .

I am also seeing similar issues with other builds. 

You can always do the checks yourself using elton on your laptop if you want your reviews faster.

Run ```elton review``` in the github repo, with ```elton review --type note``` for suspicious records.
