### ISSUE TITLE
Formatting dates in Darwin Core

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/bee-interaction-database#5]
@jhpoelen how would you format the http://rs.tdwg.org/dwc/terms/eventDate for July-August 2006? We entered as 2006-07/08 but receiving a report "176 date range [2006-07/08] appears to start after it ends"

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing! It appears that the date parsing library I use does not support the iso8601-compliant notation  ```2006-07/08``` that you use.  So, it is a bug.

**Comment by jhpoelen** [comment]
@seltmann perhaps you can transfer the issue to https://github.com/globalbioticinteractions/globalbioticinteractions ?

**Comment by seltmann** [comment]
Transferred to https://github.com/globalbioticinteractions/globalbioticinteractions/issues/535
